// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saboloxthdyyocppecgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhYm9sb3h0aGR5eW9jcHBlY2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDAxODMsImV4cCI6MjA3MjY3NjE4M30.tdB4iehXMxK1EQG9vL406Hka2t4vJPM-9sp8u72_7rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});